#!/bin/bash

mac_address="AC:BF:71:0A:7A:9F"


bluetoothctl remove $mac_address
bluetoothctl untrust $mac_address

bluetoothctl scan on &
PID=$!
sleep 5
kill $PID

bluetoothctl pair $mac_address
bluetoothctl connect $mac_address
bluetoothctl trust $mac_address
